name: Build and Release with jpackage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean package
      - name: Run jpackage (Linux)
        run: |
          chmod +x package-app.sh
          ./package-app.sh
      - name: Upload installer artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Utilities-Installer-Linux
          path: installers/PDF Utilities/bin/*

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"
      - name: Build with Maven
        run: mvn clean package
      - name: Run jpackage (macOS)
        run: |
          chmod +x package-app.sh
          ./package-app.sh
      - name: Upload installer artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Utilities-Installer-macOS
          path: installers/PDF Utilities/bin/*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"
      - name: Debug Environment
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          where java
      - name: Build with Maven
        run: mvn clean package
      - name: Run jpackage (Windows)
        run: |
          cmd /c package-app.bat
      - name: Upload installer artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Utilities-Installer-Windows
          path: installers/PDF Utilities/bin/*

  build-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install system dependencies
        shell: bash
        run: |
          dnf update -y
          dnf install -y git wget which findutils rpm-build freetype-devel libX11-devel libXext-devel libXrender-devel libXrandr-devel libXtst-devel libXi-devel xdg-utils
      - name: Install Java and Maven
        shell: bash
        run: |
          dnf remove -y java-21-openjdk java-21-openjdk-headless
          wget https://download.oracle.com/java/24/latest/jdk-24_linux-x64_bin.rpm
          rpm -ivh jdk-24_linux-x64_bin.rpm
          wget https://downloads.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
          tar -xvzf apache-maven-3.9.11-bin.tar.gz -C /opt
          export PATH=/opt/apache-maven-3.9.11/bin:$PATH
          echo "PATH=$PATH" >> $GITHUB_ENV
      - name: Set JAVA_HOME
        shell: bash
        run: |
          export JAVA_HOME=/usr/java/latest
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Java Version
        shell: bash
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -version

      - name: Build with Maven
        shell: bash
        run: mvn clean package -X
      - name: Debug Package Tools
        shell: bash
        run: |
          rpm --version
          which rpmbuild

      - name: Fix Permissions
        shell: bash
        run: |
          # Fix permissions for runtime libraries
          chmod -R 755 /tmp/jdk.jpackage*/images/opt/pdf-utilities/lib/runtime/lib/

      - name: Run jpackage (Fedora)
        run: |
          chmod +x package-app.sh
          ./package-app.sh
      - name: Upload installer artifact (Fedora)
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Utilities-Installer-Fedora
          path: installers/PDF Utilities/bin/*
